### ISSUE TITLE
How do i use it

### ISSUE THREAD

**Issue by YuuTakaheshi** [heavenly/discord_grabber#1]
how do i use it 

like how do i compile it into a exe

**Comment by heavenly** [comment]
cargo build --release

**Comment by YuuTakaheshi** [comment]
thank u <3

**Comment by YuuTakaheshi** [comment]
just one more question:
can u send a link to a tutorial or sth where i can read how 


that would save me a lot of time in terms of research

**Comment by YuuTakaheshi** [comment]
cuz i get this err

cargo: The term "cargo" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name or that the path is correct
(if included) and repeat the process.

but cargo is installed isn´t it

**Comment by YuuTakaheshi** [comment]
cuz i just unzipped the file change the weebhok and wrote cargo build --release in the terminal

**Comment by heavenly** [comment]
you need to have rustlang installed
https://rustup.rs/

**Comment by YuuTakaheshi** [comment]
ty 
it worked now

**Comment by YuuTakaheshi** [comment]
is there a way to change it that in doesn´t open terminal in background when it´s getting executed

**Comment by heavenly** [comment]
> 
> 
> is there a way to change it that in doesn´t open terminal in background when it´s getting executed

yes
https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window

**Comment by YuuTakaheshi** [comment]
ty for help <3
worked now perfect
